### ISSUE TITLE
Add an open source `LICENSE`

### ISSUE THREAD

**Issue by penyuan** [daraghhollman/horizons-wallpaper#2]
Great work! Thank you for publishing the code. Can @daraghhollman please add an open source `LICENSE` file to this repository, so that others can use and learn from you code?

It's pretty easy, with instructions in [this GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). Thanks!

**Comment by daraghhollman** [comment]
Done!

**Comment by penyuan** [comment]
> Done!

Amazing, many thanks! 😃
